version: 2.1
jobs:
 build:
    docker:
      - image: circleci/python:3.11.4
working_directory: ~/pythonProject
steps:
  #obtain repo from github
  - checkout
  #create virtual environment and install dependencies
- run:
  name: install dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -r requirements.txt
  -run: null
name: run tests
command: |
  . venv/bin/activate
  flake8 –-exclude=venv* --statistics
  # pytest -v --cov=calculator
  pytest –-junitxml=test-results/junit.xml
-store_test_results:
  path: test-results
-store_artifacts:
  path: test-results
